# SPDX-FileCopyrightText: 2025 InOrbit, Inc.
#
# SPDX-License-Identifier: MIT

version = 1
SPDX-PackageName = "inorbit-omron-connector"
SPDX-PackageSupplier = "https://github.com/inorbit-ai/flowcore-connector"

# Configuration files that don't require copyright/license headers in the file itself
# These are annotated here with MIT (same as the rest of the project)
[[annotations]]
path = "uv.lock"
SPDX-FileCopyrightText = "N/A"
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "uv.lock file"

[[annotations]]
path = ".python-version"
SPDX-FileCopyrightText = "N/A"
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "Python version file"
