# SPDX-FileCopyrightText: 2025 InOrbit, Inc.
#
# SPDX-License-Identifier: MIT

# Robot IDs must be unique. For that reason, we encourage users to pick prefixes for their robot IDs.
# To allocate a pool of robot IDs for your fleet, please contact support@inorbit.ai.
my-example-robot:
  # The timezone of the robot location as a pytz timezone (https://pythonhosted.org/pytz/#helpers)
  location_tz: America/Los_Angeles
  # Logging configuration
  logging:
    # Connector log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
    log_level: INFO
  # The type of connector
  connector_type: Gausium Phantas S

  # This is where you define custom fields specific to your robot's connector
  connector_config:
    # The serial number of the robot to connect
    serial_number: GS000-0000-000-0000
    # (optional) URL of the base API. The default value is likely correct.
    base_url: https://openapi.gs-robot.com/
    # (optional) API credentials. It is recommended to use environment variables to store these values.
    # See example.env
    client_id: ""
    client_secret: ""
    access_key_secret: ""
